
package test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Thu Nov 19 15:49:24 EST 2015
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "getInfoResponse", namespace = "http://test/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getInfoResponse", namespace = "http://test/")

public class GetInfoResponse {


}

